title:            Geir's Everything
description:      Philosophy - Sciences - Geekery - Art - Life - Coaching - Fun < Simplify Everything
copyright:        Geir Isene
url:              https://isene.org
production_url:   https://isene.org

future:      false  # publish future dated posts --  true, false (default)

highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:year/:month/:title.html

# Amount of post to show on home page
paginate: 12

comments:
  provider: disqus
  disqus:
    short_name: isene

#kramdown:
#  input: GFM
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  enable_coderay: false

#include:
#  - .htaccess

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
